### ISSUE TITLE
Make terrain features suitable for general purpose terrain mods

### ISSUE THREAD

**Issue by grondag** [grondag/Exotic-Matter#2]
Flowing terrain code currently used in Pyroclasm for basalt and lava could be used for more generic "smooth terrain" mods.  @Cadiboo expressed interest in this problem in a forge PR:  https://github.com/MinecraftForge/MinecraftForge/pull/5166#issuecomment-427547894

PRs that work towards this feature would be welcome. 

Some problems that would need to be solved:

- Replacing/rerouting existing block models to dynamic terrain models. (easy)
- Determining when/how to generate smooth terrain levels, assuming levels should be interpolated on slopes. Probably should happen during world gen. (moderate) 
- Mapping existing non-smooth block textures onto smooth terrain and not looking like crap.  (moderate)
- Allowing pack / resource pack authors to add / replace default terrain textures with a multi-block texture (easy)
- Smooth cave ceilings. Will require significant rework of terrain state and mesh generation.  Probably easiest way is to generate floor mesh (existing) and ceiling mesh (new) separately and then do a CSG union operation.  Performance could be a concern. Pre-caching might help.  (Hard)
- Performance.  If all the terrain is dynamic will be a lot of model state computations and lookups on the fly.  Current static blocks would be too many tile entities.  1.13 may allow static blocks without TileEntities (best) or can further improve state computation and caching. (Moderate)
- Compatibility.  If terrain is truly smoothed, blocks on slopes will have surfaces that don't align with a block Y boundary.  Automatic collision boxes will handle entities, but what to do about trees, plants and buildings?  The simplest path would be to not interpolate the terrain levels, but that will be unsatisfying visually. Several possibilities here, non perfect. (Very hard)

**Comment by Cadiboo** [comment]
> * Determining when/how to generate smooth terrain levels, assuming levels should be interpolated on slopes. Probably should happen during world gen. (moderate)

I think that this should be done inside rebuildChunk for each block individually (generate baked quads based on neighbours, already checked neighbours can be stored for later checks by other blocks)

> * Mapping existing non-smooth block textures onto smooth terrain and not looking like crap.  (moderate)

My initial idea for this was textures fading into each other with transparency or blending (probably pretty computationally expensive)
![154159254271021153](https://user-images.githubusercontent.com/37298044/48131000-99770300-e2e2-11e8-8817-c41f09cb64f1.gif)

> * Smooth cave ceilings. Will require significant rework of terrain state and mesh generation.  Probably easiest way is to generate floor mesh (existing) and ceiling mesh (new) separately and then do a CSG union operation.  Performance could be a concern. Pre-caching might help.  (Hard)

The Surface Nets algorithm (or Marching cubes) generates Isosurface meshes that work perfectly for floors & roofs

All my suggestions are based on implementing terrain smoothing for all blocks

**Comment by grondag** [comment]
Cadiboo - I understand your ideas - some of them are already implemented or have a partial solution in the current approach that can be extended.  I would love to get some help so let me explain a little better.  
 
Mesh generation does already happen during rebuild chunk.  The terrain models in Exotic Matter are dynamically generated based on a height map that is encoded in block states. Terrain "height" blocks (more on that later) have a height from 1-12.  The center vertex of the block top will be 1 to 12/12ths high.  

The side and corner vertices are at the midpoint between the centers of neighboring height blocks that are at the same Y level, or up to 2 Y levels below or 2 y levels above.  In other words, if two height blocks are adjacent, they will form a surface if they are within 2 blocks of each other on the Y axis. Otherwise they will form separate surfaces.

The number of combination of center height and neighbor heights is on the order of 2 ^ 54, which is why block models have to be dynamically generated.  Most of the logic for computing and representing terrain state (and deriving vertex heights) from block states is in  [TerrainState](Exotic-Matter/src/main/java/grondag/exotic_matter/terrain/TerrainState.java)

With the vertex heights computed from the block center and up to eight neighbors, it's easy to generate the mesh for the top surface of the block.

But generating a terrain surface doesn't get us block models. The smoothed surface will span many block positions, some of which may not even have a terrain block inside them.

To generate the block models, we generate a mesh with the top surface based on computed vertex heights and sides that extends down to Y - 2.  For very sloped surfaces, a vertex at a corner could be at y = 2.0 and an opposite corner at y = -2.0, and the block model is only the part between y=0 and y = 1.

The the block model, we slice the mesh along block boundaries using Constructive Solid Geometry operations.  It's hard to describe all this with words, but I don't have time right now to illustrate it.  The mesh generation is in [TerrainMeshFactory](
Exotic-Matter/blob/master/src/main/java/grondag/exotic_matter/terrain/TerrainMeshFactory.java).  If you look at that code and the generated models, hopefully you can make sense of it.  You'll also need to dig into the CSG operations used there. 

The actual mesh generation is pretty fast, and if threaded chunk rebuilds are enabled it all occurs outside the main thread.  Last time I optimized it I believe it could generate over 10,000 meshes per second, per thread.  

To be continued....

**Comment by grondag** [comment]
A little more detail on what happens in chunk rebuild....

Generated meshes are already cached for performance - both the raw geometric mesh (happens inside the mesh generator) and the textured model. I wrote specialized non-locking concurrent cache libraries to make this very fast. 

Exotic Matter also automatically generates block-breaking models, item models and collision boxes derived from the generated mesh for each block. See [SuperDispatcher](Exotic-Matter/src/main/java/grondag/exotic_matter/model/varia/SuperDispatcher.java) as a jumping-off point for all that stuff.

So, getting back to your comments, you wrote:

> The Surface Nets algorithm (or Marching cubes) generates Isosurface meshes that work perfectly for floors & roofs

Surface smoothing is what I was talking about when I wrote:

> Determining when/how to generate smooth terrain levels, assuming levels should be interpolated on slopes. Probably should happen during world gen.

The models are generated automatically from block heights, and block heights are simply block state properties.  So the part that needs to happen in world gen is generating block states that form a smooth height map. It's also necessary to generate "filler" blocks that don't have a height but are a result of smoothing.

The lava blocks in Pyroclasm generates block states as a result  the fluid simulation. It does have some basic logic for smoothing in [LavaTerrainHelper. computeIdealBaseFlowHeight] (Pyroclasm/src/main/java/grondag/pyroclasm/world/LavaTerrainHelper.java) but it is only designed to be "good enough" for lava flowing onto non-smooth terrain.

Surface Nets or another algorithm could be better.  I didn't want to tackle this until 1.13 because (apparently) world gen is changing significantly.

**Comment by grondag** [comment]
Regarding "smooth cave ceilings" - I meant that terrain blocks right now only have a smooth _top_ surface.  If they also had a smooth bottom surface that would probably be enough.

A relatively simple way to do this would be to give terrain blocks a "bottom" level in addition to  a top. I guess this could be called a "depth map", but basically it's an upside-down height map.

This would require that block states have potentially two attributes.  (Although most won't - they will have one or the other.). This is doable in 1.12 but might require multiple blocks.  It should be trivial in 1.13.

Mesh generation could reuse the current logic but could require two passes. One pass would be the current surface mesh.  The second would be a depth mesh.  The CSG intersection of those two meshes would produce the block model.  

You wrote:
>My initial idea for this was textures fading into each other with transparency or blending (probably pretty computationally expensive)

That could work. The model generation logic has hooks to do things like that.  See [VertexProcessor](Exotic-Matter/src/main/java/grondag/exotic_matter/model/painting/VertexProcessor.java) and subclasses in Pyroclasm for examples.  

Blending in vanilla rendering does require translucency / blending which is indeed expensive during the render loop because it needs multiple passes and because the vertices have to be resorted when the player moves. 

The Acuity rendering API will avoid the penalty by combining the two layers in a shader and render it in the solid block layer in one pass.  (Won't work for blocks that really are translucent.) 

If you're interested in giving this a try, my suggestion is creating a new mod that uses Exotic Matter as a dependency and start with blocks that have a smooth top surface, like gravel, sand, dirt/grass, etc. 

The cool basalt blocks in Pyroclasm would be a good template to start from. They are instances of [TerrainDynamicBlock](Exotic-Matter/src/main/java/grondag/exotic_matter/terrain/TerrainDynamicBlock.java) declared in [Pyroclasm/src/main/java/grondag/pyroclasm/init/ModBlocks.java](url)

And then as you run into problems or limitations in Exotic-Matter, you could do a pull request or log an issue to add what you need.

Lastly, what is your idea for handling plants?

**Comment by Cadiboo** [comment]
I think all this is way over my head, what do you mean by plants? If you mean rendering them on smooth terrain, I think you could either extend/move their rendering down or make sure that the block underneath them always has a flat upper surface

**Comment by grondag** [comment]
This feature is being incorporated in the Exotic Matter 2 library for Fabric. It will not be coming to Forge.
