### ISSUE TITLE
Optifine Compatibility?

### ISSUE THREAD

**Issue by RViper80** [grondag/Exotic-Matter#6]
With Opti(fabric/fine) loaded, the game crashes when trying to view any of your blocks in REI's item list.

Crashlog: https://pastebin.com/MNctvZwe

Edit:  Hmm... I have heard Optifine really messes with rendering stuff, and you're using your Canvas shader library, so can't say I expect anything here. :)   Since I really only use Optifine for the shaders, guess I'll have to do without for now, and hope maybe eventually Canvas can support those kinds of shaders instead even though it's not designed to.

**Comment by grondag** [comment]
Yeah, sorry.  It probably should work with OptiFine / Indigo / OptiFabric and maybe it will at some point, but given that OF is closed source it's too much work for me to troubleshoot these issues.

Even so, thank you for your interest in XM.
