### ISSUE TITLE
Whenever I try to access an exotic block item from my inventory, it crashes.

### ISSUE THREAD

**Issue by Lieutenant2014** [grondag/Exotic-Matter#8]
not enought crashes says exotic matter broke it
[crash-2020-07-14_13.42.19-client.txt](https://github.com/grondag/Exotic-Matter/files/4920343/crash-2020-07-14_13.42.19-client.txt)

**Comment by grondag** [comment]
Hello, thank you for reporting. Unfortunately Exotic Matter / Exotic Blocks and other mods that use the Fabric Rendering API are incompatible with Sodium. Sodium has plans to add support, but for now I've added a tag to XM to make this more clear at load time.

In the interim, you can try [Canvas Renderer](https://www.curseforge.com/minecraft/mc-mods/canvas-renderer), but it is not as fast as Sodium on most hardware.
