### ISSUE TITLE
Crash when trying to search through tabs

### ISSUE THREAD

**Issue by Sunconure11** [grondag/Exotic-Matter#9]
https://pastebin.com/SUyB57u6

**Comment by grondag** [comment]
Hello, thank you for reporting.  Unfortunately Exotic Matter / Exotic Blocks and other mods that use the Fabric Rendering API are incompatible with Sodium.  Sodium has plans to add support, but for now I've added a tag to XM to make this more clear at load time. 

In the interim, you can try [Canvas Renderer](https://www.curseforge.com/minecraft/mc-mods/canvas-renderer), but it is not as fast as Sodium on most hardware.
